name: tap_to_expand
description: This package is to build expandable widget fast and easy with few lines and you can customize it to whatever!.
version: 0.7.1
homepage: https://github.com/AbdallahAwd/tap_to_expand

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.24.9

flutter:
